runtime: php55
api_version: 1
threadsafe: true

handlers:

- url: /
  script: login.php

- url: /register
  script: register.php

- url: /main
  script: main.php

- url: /game
  script: game.php

- url: /account
  script: account.php

- url: /win
  script: win.php

- url: /lose
  script: lose.php

- url: /leaderboards
  script: stats.php